source 'https://Jasperav@bitbucket.org/Jasperav/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
target 'JVMiddleTextView_Tests' do
  pod 'JVMiddleTextView', :path => '../'
  
  
end
